apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: image
  template:
    metadata:
      labels:
        app: image
    spec:
      containers:
      - name: image
        image: demokinjal/task1-java:${VERSION}
        imagePullPolicy: Always
        ports:
        - containerPort: 9090
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: image
    k8s-app: image
  name: image
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 9090
  type: LoadBalancer
  selector:
    app: image
